name: build .exe

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --no-cache-dir --prefer-binary -r requirements.txt
      - name: Add Qt6 DLLs to PATH
        shell: pwsh
        run: |
          $qtBin = Join-Path $Env:pythonLocation 'Lib\site-packages\PyQt6\Qt6\bin'
          Add-Content $env:GITHUB_PATH $qtBin
#      - name: Debug Environment
#        run: |
#          echo "PATH: $PATH"
#          echo "SHELL: $SHELL"
#        shell: bash
      - run: ui/make.bat
      - uses: Nuitka/Nuitka-Action@v1.3
        with:
          script-name: mqtt_live.py
          msvc: latest
          mode: standalone
          windows-console-mode: disable
          enable-plugins: pyqt6
#      - uses: actions/upload-artifact@v4
#        with:
#          name: mqtt_live
#          path: build/mqtt_live.dist/
      - run: cp LICENSE build/mqtt_live.dist/
      - uses: thedoctor0/zip-release@0.7.6
        with:
          filename: mqtt_live.zip
          directory: build/mqtt_live.dist/
          type: 7z
#      - run: dir -s
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build/mqtt_live.dist/mqtt_live.zip
